Create analytics script
18F/identity-idva-monitoring pull request #179
Opened 2022-04-12 13:38 UTC by mikeisen1

This PR creates the script used for the querying and preparation of Elasticsearch data to be used in subsequent data visualization, as existing data visualization tools do not currently support the necessary Elasticsearch queries for analysis. The analytics script does the following:
- Create script to query data, for any time frame, from an Elasticsearch server
- Define bulk actions, using query results, to send to analytics indices
- Create Elasticsearch analytics indices by a given timeframe, if they do not exist
- Send the bulk request to upload the data to the appropriate index

2022-04-15 14:50 UTC, dzaslavskiy requested changes

2022-04-15 14:50 UTC, dzaslavskiy commented on .github/workflows/deploy-analytics-scripting.yaml
> +on:
the trigger should be like the deploy scripts for the other apps, it only deploys the script when it changes. we will be triggering the runs separately.

2022-04-15 14:50 UTC, dzaslavskiy commented on analytics-scripting/runtime.txt
> +python-3.8.x
does it need to be python 3.8?

2022-04-15 14:50 UTC, dzaslavskiy commented on analytics-scripting/analytics_script.py
> +flowId = "t035KrLTyPv3jJao4jzwRrSzyV2gU1oK"
make flowid, time range optional commandline args

2022-04-15 14:50 UTC, dzaslavskiy commented on analytics-scripting/analytics_script.py
> +    index_to_update = "dev-analytics-%s" % max_date.strftime('%Y.%m.%d')
use f string

2022-04-15 14:50 UTC, dzaslavskiy commented on analytics-scripting/analytics_script.py
> +      "_id": bucket["key"]["agg"],
do we need to set this id or can we let es set it?

2022-04-15 14:50 UTC, dzaslavskiy commented on analytics-scripting/analytics_script.py
> +  helpers.bulk(es, bulk_actions)
not looking at response from bulk action request? I would think you need to if there were errors

2022-04-15 14:50 UTC, dzaslavskiy commented on analytics-scripting/requirements.txt
> +elasticsearch==7.1.0
is this the correct version of the library for our es version?

2022-04-15 14:50 UTC, dzaslavskiy commented on .github/workflows/deploy-analytics-scripting.yaml
> +        run: cf push
need be creating a task not deploying and running app

2022-04-15 16:22 UTC, folksgl commented
Please use the Python [Black Formatter](https://black.readthedocs.io/en/stable/).

2022-04-18 13:19 UTC, mikeisen1 commented on analytics-scripting/requirements.txt
> +elasticsearch==7.1.0
We're running es version 7.4.2. However, there is no Elasticsearch Python client available for that version. The previous release of the python client that is available is 7.1.0 and the next release that is available is 7.5.1.

2022-04-18 13:24 UTC, mikeisen1 commented on analytics-scripting/analytics_script.py
> +      "_id": bucket["key"]["agg"],
This is the document id. bucket["key"]["agg"] is the interactionId, which needs to be in the document. We could not include the above line, allow elasticsearch python client to generate a document id, and include the interactionId in the document source. However, since interactionId is unique, it makes sense to have it be the document identifier.

2022-04-18 14:48 UTC, folksgl commented on analytics-scripting/requirements.txt
> +elasticsearch==7.1.0
This seems relevant https://elasticsearch-py.readthedocs.io/en/v8.1.2/#compatibility. Seems like we can use the latest v7 of the client? Does that sound correct @dzaslavskiy?

2022-04-18 18:40 UTC, dzaslavskiy commented on analytics-scripting/requirements.txt
> +elasticsearch==7.1.0
The docs you linked to on the latest version of es say that client are forward compatible and does not guarantee full backwards compatibility implying we should be using 7.1.0. The docs on older versions of es up to version v7.14.0 say that client are major version compatible implying we should be using latest v7.

2022-04-18 20:35 UTC, folksgl commented on analytics-scripting/manifest.yaml
> +      python3 analytics_script.py http://identity-idva-es-proxy-dev.apps.internal
Why are we using the elasticsearch proxy here? There shouldn't really be a need, since we're writing custom code, and there are plenty of docs available showing how to sign requests to AWS.

2022-04-18 20:39 UTC, folksgl commented on analytics-scripting/requirements.txt
> +elasticsearch==7.1.0
Why are we using the elasticsearch package instead of `opensearch-py` as seems to be the recommendation here: https://docs.aws.amazon.com/opensearch-service/latest/developerguide/request-signing.html#request-signing-python

2022-04-19 15:29 UTC, folksgl requested changes

2022-04-19 15:29 UTC, folksgl commented on analytics-scripting/analytics_script.py
> +        return res["aggregations"]["types_count"]["hits"]["hits"][0]["sort"][0] - 300000
300,000 is a magic number

2022-04-19 15:29 UTC, folksgl commented on analytics-scripting/analytics_script.py
> +    if len(query_result["aggregations"]["my_buckets"]["buckets"]) > 0:
Are you trying to check if the list is not empty? The pythonic way of doing this is
```
if not <listname>:
  do_something()
```

2022-04-19 15:29 UTC, folksgl commented on analytics-scripting/analytics_script.py
> +        query["aggs"]["my_buckets"]["composite"]["after"] = {"agg": after_key}
This catches a lot of things, which is bad. The case you're trying to solve here is that on the first run, the key doesn't yet exist. This can be checked with a simple `if` statement, create the key and continue on your way. What's dangerous about this is that you're using exception handling for something that's not really exceptional. And if we get a `KeyError` for something other than the very specific case where we expect it, we're still trying to perform key lookups! That could trigger other `KeyErrors`. This can likely be refactored to look similar to the following:
```
if (key doesn't exist):
  create_key_here

try:
  query["some"]["key"]["lookups"]
except KeyError:
  # Now something is actually wrong, and the data doesn't look like we expected.

2022-04-19 15:29 UTC, folksgl commented on analytics-scripting/analytics_script.py
> +        query["aggs"]["my_buckets"]["composite"]["after"] = {"agg": after_key}
Additionally there are several places where we're getting down to the same data (`query["aggs"]["my_buckets"]["composite"]["after"]` for example). You do a good job above just naming these as variables. This code will likely read better if you continue that pattern throughout, and isolate error checking to those places.

2022-04-19 15:29 UTC, folksgl commented on analytics-scripting/analytics_script.py
> +def send_query_and_evaluate_result(es, query, num_composite_buckets, cmdLineParser):
Are you running `pylint` on this code? When it is taken out of draft, I will be running it as part of the review process and it needs to come back relatively free of warnings/errors.

2022-04-19 15:32 UTC, folksgl commented on analytics-scripting/analytics_script.py
> +        query["aggs"]["my_buckets"]["composite"]["after"] = {"agg": after_key}
You may want to look at using [dict.setdefault()](https://docs.python.org/3/library/stdtypes.html#dict.setdefault)

2022-04-19 19:43 UTC, mikeisen1 commented on analytics-scripting/analytics_script.py
> +        query["aggs"]["my_buckets"]["composite"]["after"] = {"agg": after_key}
For this specific example, we do not need the try/except block as `query` was manually constructed. However, there are instances in the script where we could see a `KeyError` which could potentially result from issues in a query response. For these, is it best to propagate the exception down after which we get an alert that the task crashed, or something else?

2022-04-19 20:40 UTC, folksgl commented on analytics-scripting/analytics_script.py
> +        query["aggs"]["my_buckets"]["composite"]["after"] = {"agg": after_key}
If we get a keyerror when we don't expect it when trying to manipulate this data, I would err on the side of not trying to perform any changes to it until we understand what happened. Why doesn't the data look like we expected? I don't think that's something we can predict and handle gracefully here. @dzaslavskiy thoughts on that?

2022-04-20 15:08 UTC, mikeisen1 commented on .github/workflows/deploy-analytics-scripting.yaml
> +on:
Since the script is running as a task in the kibana app, it is not being deployed as an app. Rather, it will be run as a task on the app on a schedule of every 5 minutes. Additionally, since a scheduled job only runs from the default branch of the repository, changes made to the script will only run once merged into the default branch.

2022-04-20 15:08 UTC, folksgl commented on kibana/analytics-scripting/analytics_script.py
> +        query_composite["after"] = {"agg": after_key}
The comments are helpful but I don't think the if statement is necessary. Can't this just be simplified to
```suggestion
    query_composite.setdefault("after", {})
    query_composite["after"] = {"agg": after_key}
```

2022-04-20 15:33 UTC, mikeisen1 commented on analytics-scripting/analytics_script.py
> +  helpers.bulk(es, bulk_actions)
The response could display errors if there are issues with the construction of the request. However, this should not be an issue as the mapping of the documents sent and the indices are known and the requests are built such that these will not occur unless there are changes to the index mappings or data itself. Other possible errors, such as `index_not_found_exception` are prevented and `cluster_block_exception` (occurs when a machine is low on disk space) should not be handled by this script (nor am I sure it needs to). There is a generic BulkIndexError as well as connection errors (maybe retry?) which could be looked at.

2022-04-20 16:37 UTC, mikeisen1 commented on kibana/analytics-scripting/analytics_script.py
> +        index_to_update = f"dev-analytics-{max_date.strftime('%Y.%m.%d')}"
Currently, our Elasticsearch indices are all prefixed by "dev" (none for "test" or "prod"), so we named this "dev-analytics". If, in the future, we have indices prefixed by "test" or "prod", it's not difficult to do so for the analytics indices in the script depending on the environment.

2022-04-20 21:09 UTC, dzaslavskiy requested changes

2022-04-20 21:09 UTC, dzaslavskiy commented on kibana/analytics-scripting/analytics_script.py
> +def add_keys_if_not_exist(dictionary, keys):
It would be great if you could add some type hints to these functions to make it easier to understand what is going on.

2022-04-21 20:11 UTC, mikeisen1 commented on kibana/analytics-scripting/analytics_script.py
> +DEFAULT_NUM_COMPOSITE_BUCKETS = 10
10 is the default. We still have to choose the number, but it could definitely be increased to a number larger than 10.

2022-04-22 01:48 UTC, dzaslavskiy commented on kibana/analytics-scripting/analytics_script.py
> +ANALYTICS_INDEX_PATTERN = "dev-skanalytics-*"
you changed the name of the index?

2022-04-22 07:52 UTC, dzaslavskiy requested changes

2022-04-22 07:52 UTC, dzaslavskiy commented on kibana/manifest.yaml
> +  - name: analytics-scripting
This does not seem quite right. We want to push script as a task and then run it later. This would not accomplish that because the script would run when pushed. Is this a limitation of cloudfoundry?

2022-04-22 12:49 UTC, mikeisen1 commented on kibana/analytics-scripting/analytics_script.py
> +ANALYTICS_INDEX_PATTERN = "dev-skanalytics-*"
That is a mistake, should be `dev-analytics` not `dev-skanalytics`.

2022-04-22 13:14 UTC, mikeisen1 commented on kibana/manifest.yaml
> +  - name: analytics-scripting
It appears so, as according to [documentation](https://docs.cloudfoundry.org/devguide/deploy-apps/manifest-attributes.html), there isn't a way to use an application manifest and its attributes to push a script as a task.

2022-04-22 15:40 UTC, folksgl commented on kibana/analytics-scripting/analytics_script.py
> +        curr_dict = curr_dict[key]
This one took me a minute -- I would highly recommend renaming this method to `add_nested_keys()`, as `add_keys_if_not_exist` subtly implies that my dict will remain flat. I also think you can simplify your loop here. Isn't the following functionally equivalent to what you have now?

```suggestion
def add_keys_if_not_exist(dictionary: dict, keys: list):
    """
    Adds keys, in a nested format, to the dictionary if the keys do not exist.
    """
    curr_dict = dictionary
    for key in keys:
        curr_dict = curr_dict.setdefault(key, {})
```

2022-04-25 16:11 UTC, dzaslavskiy commented on kibana/manifest.yaml
> +  - name: analytics-scripting
Unless @folksgl knows of a way to do this, I seems we need to deploy this as separate app. please reference orchestration/manifest for that. Add github workflow for that.

2022-04-25 16:11 UTC, dzaslavskiy requested changes

2022-04-25 16:11 UTC, dzaslavskiy commented on kibana/manifest.yaml
> +  - name: analytics-scripting
Unless @folksgl knows of a way to do this, I seems we need to deploy this as separate app. please reference orchestration/manifest for that. Add github workflow for that.

2022-04-25 16:33 UTC, dzaslavskiy requested changes

2022-04-25 16:33 UTC, dzaslavskiy commented on kibana/analytics-scripting/analytics_script.py
> +    create_documents_and_send_bulk_request(buckets, source)
I think this function is factored incorrectly. You want helper functions to one specific thing. I cannot say exactly how to fix this but the structure needs to be re-worked. I would start by just in-lining this call and see what makes sense from there.

2022-04-25 19:59 UTC, dzaslavskiy requested changes

2022-04-25 19:59 UTC, dzaslavskiy commented on .github/workflows/analytics-scripting.yaml
> +on:
should trigger on push/pr

2022-04-25 19:59 UTC, dzaslavskiy commented on kibana/analytics-scripting/analytics_script.py
> +        "aggs": {
why use aggs here? Isn't it possbile to just query and sort by timestamp?

2022-04-25 19:59 UTC, dzaslavskiy commented on kibana/analytics-scripting/analytics_script.py
> +def create_index_if_doesnt_exist(new_index: str):
rename to just create_index. The comment should make clear the "if doesn't exit" part

2022-04-25 19:59 UTC, dzaslavskiy commented on kibana/analytics-scripting/analytics_script.py
> +    if query_result["aggregations"]["my_buckets"]["buckets"]:
would this ever be false?

2022-04-25 19:59 UTC, dzaslavskiy commented on kibana/analytics-scripting/analytics_script.py
> +    elasticsearch, query_avg_response_time, DEFAULT_NUM_COMPOSITE_BUCKETS, arguments
you pass elasticserach into the function here but, refrence the global variable elasticsearch in the other functions.

2022-04-25 19:59 UTC, dzaslavskiy commented on kibana/analytics-scripting/analytics_script.py
> +    elasticsearch, query_avg_response_time, DEFAULT_NUM_COMPOSITE_BUCKETS, arguments
I think it is poor form to pass the args object to the function. Keep args in the top level function and pass only the values

2022-04-25 19:59 UTC, dzaslavskiy commented on kibana/analytics-scripting/analytics_script.py
> +        query_result = es_cluster.search(index=SK_INDEX_PATTERN, body=query)
Why does this line return different values on subsequent invocations? Is it modified inside of process_composite_aggregation_data?

2022-04-25 20:44 UTC, dzaslavskiy requested changes

2022-04-25 20:44 UTC, dzaslavskiy commented on kibana/analytics-scripting/analytics_script.py
> +    try:
add a comment here explaining the two cases handled here.

2022-04-25 20:44 UTC, dzaslavskiy commented on kibana/analytics-scripting/analytics_script.py
> +    # Composite aggregation queries only return a specified number of buckets,
this comment is too big. Ideal the code is self explanatory but if not it is best if comments are short precise. Longer comments can go at the top of a function in the doc string, top of the file, or readme.

2022-04-25 20:44 UTC, dzaslavskiy commented on kibana/analytics-scripting/analytics_script.py
> +    try:
add a comment here explaining the two cases being handled here

2022-04-25 20:44 UTC, dzaslavskiy commented on kibana/analytics-scripting/manifest.yaml
> +        --flow_id t035KrLTyPv3jJao4jzwRrSzyV2gU1oK
flow id should probably be an env var that is passed in.

2022-04-25 20:44 UTC, dzaslavskiy commented on kibana/analytics-scripting/manifest.yaml
> +---
Here is something to try. Add the this analytics script to kibana maniffest as a second process and set instance count to zero. Then you should be able to run it as a task later. I think that would a good solution if it works

2022-04-25 20:44 UTC, dzaslavskiy commented on .github/workflows/analytics-scripting.yaml
> +---
I don't like the name 'analytics-scripting' can you change it something nicer?

2022-04-26 03:28 UTC, mikeisen1 commented on kibana/analytics-scripting/analytics_script.py
> +    if query_result["aggregations"]["my_buckets"]["buckets"]:
It would be false if the number of buckets in the composite aggregation query is a multiple of `DEFAULT_NUM_COMPOSITE_BUCKETS`.

2022-04-26 13:48 UTC, mikeisen1 commented on kibana/analytics-scripting/analytics_script.py
> +    elasticsearch, query_avg_response_time, DEFAULT_NUM_COMPOSITE_BUCKETS, arguments
This was changed to using the global variable elasticsearch.

2022-04-26 15:02 UTC, mikeisen1 commented on .github/workflows/analytics-scripting.yaml
> +on:
If we run the script as a process in the kibana app, we do not need this workflow.

2022-04-26 18:57 UTC, dzaslavskiy requested changes

2022-04-26 18:57 UTC, dzaslavskiy commented on kibana/idvametrics/analytics_script.py
> +    get_start_date(arguments),
isn't there a mechanism for specifying the default value of an arg that would simplify this?

2022-04-26 18:57 UTC, dzaslavskiy commented on kibana/idvametrics/analytics_script.py
> +    os.environ["FLOW_ID"],
This should still be an arg here, We will get the value from an environment variable when we execute the command

2022-04-26 18:57 UTC, dzaslavskiy commented on kibana/manifest.yaml
> +  - type: worker
have you tested this? does it work as expected?

2022-04-26 21:40 UTC, dzaslavskiy commented on kibana/idvametrics/analytics_script.py
> +    "size": 0,
what is the difference between "hits": {"top_hits": {"_source": ["companyId", "flowId"], "size": 1}} and setting "size": 1,

2022-04-26 21:58 UTC, dzaslavskiy requested changes

2022-04-26 21:58 UTC, dzaslavskiy commented on kibana/idvametrics/analytics_script.py
> +    # running the query against dev-skevents in elasticsearch
please make these comments more succinct. move any explanatory text to the doc string or readme as appropriate

2022-04-26 21:58 UTC, dzaslavskiy commented on kibana/idvametrics/analytics_script.py
> +    for bucket in buckets:
please make these comments more succinct. move any explanatory text to the doc string or readme as appropriate

2022-04-26 21:59 UTC, dzaslavskiy commented on kibana/idvametrics/README.md
> +Scripts for accessing and preparing IDVA Login data for use in visualization analytics.
readme needs to be updated

2022-04-26 22:01 UTC, dzaslavskiy commented
Move from draft when ready.

2022-04-28 09:56 UTC, dzaslavskiy requested changes

2022-04-28 09:56 UTC, dzaslavskiy commented on kibana/idvametrics/analytics_script.py
> +        "_id": document_id,
We need to make sure the id is unique even when we add other types of metrics to the index.

2022-04-28 09:56 UTC, dzaslavskiy commented on kibana/idvametrics/analytics_script.py
> +def process_composite_aggregation_data(query_result: dict):
We should handle the case where an interactionId might have already been saved to another index.

2022-04-28 20:23 UTC, folksgl commented on kibana/idvametrics/analytics_script.py
> +        return int(current_timestamp)
Only line 89 could trigger a `KeyError`, the other lines need to be moved out of the try/except block. As a general rule of thumb, don't include code in try/catch blocks that's not related to the possible exception you're trying to handle.
```suggestion
    try:
        # Attempting to get the time of five minutes prior to the most recent timestamp (tsEms)
        # of a document in the analytics index.
        latest_timestamp = parser.parse(res["hits"]["hits"][0]["_source"]["tsEms"])
    except KeyError:
        # Nothing in the analytics index for the given flow_id, so use the current time.
        latest_timestamp = datetime.now()
        
    five_mins_prior = latest_timestamp - FIVE_MINS
    return int(five_mins_prior.timestamp())
```

2022-04-29 14:34 UTC, dzaslavskiy submitted a review, later dismissed

2022-05-11 15:56 UTC, folksgl approved these changes

2022-05-11 16:21 UTC, merged