Create ids mapping script
18F/identity-idva-monitoring pull request #192
Opened 2022-05-10 18:09 UTC by mikeisen1

Creates a script that maps flow ids to flow names and node ids to node titles. This script is also added as a task to Cloud Foundry.

2022-05-10 18:12 UTC, mikeisen1 commented
For this PR, I was unsure of which analytics index the mapping data should be added to. For now, the script relies on the time in which the script is run. That is obviously not the solution, but I just used that as a placeholder. One thought would be to add the mapping to the analytics index representing the day which the flow was created. Thoughts on that or a separate approach?

2022-05-11 14:52 UTC, dzaslavskiy requested changes

2022-05-11 14:52 UTC, dzaslavskiy commented on kibana/idsnamesmapping/mapping.py
> +    auth = {"email": "idva@gsa.gov", "password": "vBtCVyI@v0oqgxBejd!sJz&ZJc"}
Lets try to not commit usernames and passwords to public repos. Also api base url.

2022-05-11 14:53 UTC, dtaylor-edc commented on kibana/idsnamesmapping/mapping.py
> +    idva_flows_url = "https://idva-api-dev.app.cloud.gov/v1/flows"
Why are we hardcoding a dev url when the expectation is this should be runnable in any environment without changes

2022-05-11 14:54 UTC, dtaylor-edc commented on kibana/idsnamesmapping/mapping.py
> +    login_url = "https://idva-api-dev.app.cloud.gov/v1/customers/login"
Why are we hardcoding a dev url when the expectation is this should be runnable in any environment without changes

2022-05-11 18:56 UTC, folksgl requested changes

2022-05-11 18:56 UTC, folksgl commented on kibana/idsnamesmapping/mapping.py
> +    bulk_actions = []
Variable initialization should live as close to possible to first usage of the variable.

2022-05-11 18:56 UTC, folksgl commented on kibana/idsnamesmapping/README.md
> +Script for mapping idva flow ids to flow names and node ids to node titles.
Go a little more in-depth here on what this script is doing. Be sure to give context around the problem this script is here to solve. Why do we need this script in the first place?

Additionally, please rename the directory these files are in. If this directory is for scripts that operate on the ES data, perhaps `scripts` or `data_processing`. Something meaningful and preferably in snake_case or camelCase so that words are distinct.

2022-05-11 18:56 UTC, folksgl commented on kibana/manifest.yaml
> +        --flowsurl https://idva-api-((ENVIRONMENT_NAME)).app.cloud.gov/v1/flows
Everything up to this point indicates that this code is supposed to be a script (i.e. we run it when we need to and that's it) but adding this as a worker process makes this into a long-running process that is part of the kibana app. Which are we doing? Adding a worker process or running a script every once in a while?

2022-05-11 18:56 UTC, folksgl commented on kibana/idsnamesmapping/mapping.py
> +    access_token = requests.post(login_url, data=auth).json()["access_token"]
Unhandled KeyError

2022-05-11 18:56 UTC, folksgl commented on kibana/idsnamesmapping/mapping.py
> +    flows = requests.get(idva_flows_url, headers=header).json()["flowsInfo"]
Unhandled KeyError

2022-05-11 18:56 UTC, folksgl commented on kibana/idsnamesmapping/mapping.py
> +    access_token = requests.post(login_url, data=auth).json()["access_token"]
`requests.post()` returns a `requests.Response` object, which could be a non-200 response.

2022-05-11 18:56 UTC, folksgl commented on kibana/idsnamesmapping/mapping.py
> +    flows = requests.get(idva_flows_url, headers=header).json()["flowsInfo"]
`requests.get()` returns a `requests.Response` object, which could be a non-200 response.

2022-05-11 18:56 UTC, folksgl commented on kibana/idsnamesmapping/mapping.py
> +                  f'{ANALYTICS_INDEX_PATTERN}-{datetime.now().date().strftime("%Y.%m.%d")}'
Running `black` v22.3.0 reformats this. Make sure you're running the most up-to-date version of black on this.

2022-05-11 18:56 UTC, folksgl commented on kibana/idsnamesmapping/mapping.py
> +                bulk_actions.append(bulk_action)
Check for special case first, then handle it. That way business logic stays mostly flat
```suggestion
            if not node_title:
                continue

            # Only add the node id to title mapping if the title is defined for the node
            document = create_mapping_document(
                flow_id, flow_name, node_id, node_title
            )
            document_id = create_document_id(flow_id, node_id)
            # the index the data is added to depends on the current date
            index_to_update = \
              f'{ANALYTICS_INDEX_PATTERN}-{datetime.now().date().strftime("%Y.%m.%d")}'
            bulk_action = create_bulk_index_action(
                index_to_update, document_id, document
            )
            bulk_actions.append(bulk_action)
```

2022-05-11 19:03 UTC, mikeisen1 commented
Closing as the mapping efforts do not need to be in a separate script, index, or their own Elasticsearch documents. The new PR can be found [here](https://github.com/18F/identity-idva-monitoring/pull/193).

2022-05-11 19:03 UTC, closed without merging