Feature/add ids to names mapping
18F/identity-idva-monitoring pull request #193
Opened 2022-05-11 16:15 UTC by mikeisen1

Pull data for and add mapping from flow ids to flow names and node ids to node names, as that mapping is not provided by the Elasticsearch data.

2022-05-11 19:33 UTC, mikeisen1 commented on kibana/idvametrics/analytics_script.py
> +    flows = requests.get(flows_url, headers=header).json()["flowsInfo"]
@folksgl and @dzaslavskiy, which is the better approach in the case of a `KeyError`: Stop running the script or have flow/node names be `None`?

2022-05-11 21:22 UTC, dzaslavskiy requested changes

2022-05-11 21:22 UTC, dzaslavskiy commented on kibana/manifest.yaml
> +        --flows_url https://idva-api-((ENVIRONMENT_NAME)).app.cloud.gov/v1/flows
the arg here should be base_url. the paths are fixed

2022-05-11 21:23 UTC, dzaslavskiy commented on kibana/manifest.yaml
> +        --email ((EMAIL))
this should be username or user id

2022-05-11 21:31 UTC, mikeisen1 commented
@folksgl, in the manifest, when we create this script as a worker process under the kibana app, we are still able to run the script every once in a while. Per the [documentation](https://cli.cloudfoundry.org/en-US/v8/run-task.html), using `--process` in the `run-task` command will run the script as a one-off task.

2022-05-12 06:54 UTC, dzaslavskiy requested changes

2022-05-12 06:54 UTC, dzaslavskiy commented on kibana/manifest.yaml
> +        --base_url https://idva-api-((ENVIRONMENT_NAME)).app.cloud.gov/v1/flows
There should only be one arg here: base_url

2022-05-17 02:05 UTC, dzaslavskiy requested changes

2022-05-17 02:05 UTC, dzaslavskiy commented on kibana/idvametrics/analytics_script.py
> +    access_token = requests.post(login_url, data=auth).json()["access_token"]
handle non success response

2022-05-17 02:05 UTC, dzaslavskiy commented on kibana/manifest.yaml
> +        --base_url https://idva-api-((ENVIRONMENT_NAME)).app.cloud.gov/v1
please move the /v1 into specific url and out of the base url

2022-05-17 14:59 UTC, dzaslavskiy approved these changes

2022-05-17 18:44 UTC, folksgl requested changes
> @folksgl, in the manifest, when we create this script as a worker process under the kibana app, we are still able to run the script every once in a while. Per the [documentation](https://cli.cloudfoundry.org/en-US/v8/run-task.html), using `--process` in the `run-task` command will run the script as a one-off task.

@mikeisen1, @dzaslavskiy I still don't understand why this is being added as a worker process at all. Perhaps I'm missing something, in which case please walk me through the logic here.

My understanding of worker processes is that they're supposed to be continually doing some useful work such as processing a queue or similar backend work that has to happen, but doesn't require accepting and processing web requests directly. **However**, this looks like it will run once and then exit. The entry points to the script are essentially the `get_mappings()` and `send_query_and_evaluate_result()` functions, neither of which contain any logic to continually execute after being run the first time as far as I can tell. If this script is not doing doing _**continuous**_ work, then its essentially just a CF Task, and has no reason to be cemented as a worker process.

2022-05-17 19:43 UTC, dzaslavskiy commented
@folksgl Perhaps I am misunderstanding some aspect of the CF interface, but I don't think there is another way to set up a process that then runs on demand. It is being invoked as a task and does not run continuously. It is present in the manifest in order set it up for later execution.

2022-05-17 20:17 UTC, folksgl commented
@dzaslavskiy Can the following not completely replace the worker process in the manifest? I haven't run this myself, but it seems to be possible to run commands as tasks without having to set up any extra cf resources in the `kibana` app so long as the command can be run on the container as-is.
`cf run-task kibana --command '~/path/to/analytics-script ...'`

Using `run-task` like this would probably require kibana to add the `python_buildpack` as well which I guess is less than ideal. But I'm also not sure what happens to a worker process that just exits -- does it get re-started non-stop? Is it marked as crashed after so many attempts?

If we do want an app that's just for running this task, it should likely be a separate app (whether in the same manifest or not) and follow the [Run a Task on an App with cf CLI v7](https://docs.cloudfoundry.org/devguide/using-tasks.html#run-tasks) steps in the CF docs, using `cf push APP-NAME --task` to set the process up for repeated execution.

2022-05-17 21:17 UTC, dzaslavskiy commented
Yes you can just run the command but that seems awkward and inconvenient. The worker process is started at 0 instances (stopped) and stays that way. the task just runs of the worker manifest. separate manifest is how I did it before with sk.

2022-05-18 18:45 UTC, folksgl approved these changes

2022-05-18 19:28 UTC, merged