Feature/generalize analytics scripting
18F/identity-idva-monitoring pull request #194
Opened 2022-05-18 19:45 UTC by mikeisen1

This PR generalizes #193 so that any desired query can be run and all necessary data is pulled into the analytics index. It also separate the `kibana` and `idvametrics` apps to make it simple and clearer how the tasks should be separated.

2022-05-19 17:49 UTC, dzaslavskiy requested changes
please fix this pr to take into account the changes made in the previous prs. As it currently stands, the pr only adds new files duplicating the existing ones.

2022-05-19 18:43 UTC, dzaslavskiy requested changes

2022-05-19 18:43 UTC, dzaslavskiy commented on .github/workflows/deploy-idvametrics.yaml
> +      - name: Deploy Analytics Scripting
I believe this should deploy as a task

2022-05-19 18:43 UTC, dzaslavskiy commented on idvametrics/manifest.yaml
> +    instances: 0
when deployed as a task, I don't think it is necessary to set instances to 0

2022-05-19 18:43 UTC, dzaslavskiy commented on idvametrics/manifest.yaml
> +        --password "$PASSWORD"
how does the password get set?

2022-05-19 18:43 UTC, dzaslavskiy commented on .github/workflows/deploy-idvametrics.yaml
> +        run: cf push --vars-file vars.yaml
not all the variables in the manifest are satisfied

2022-05-19 18:43 UTC, dzaslavskiy commented on idvametrics/analytics_query.py
> +def convert_end_date_to_int_date(end_date: str) -> int:
what is an end date?

2022-05-19 18:43 UTC, dzaslavskiy commented on idvametrics/analytics_query.py
> +    def __init__(self, **kwargs):
do the args need to be a dictionary? Not sure about the conventions on this but it seem like it would be better if they where separate args

2022-05-19 18:43 UTC, dzaslavskiy commented on idvametrics/upload_metrics.py
> +    login_url = f"{base_url}/customers/login"
v1 missing

2022-05-19 20:57 UTC, mikeisen1 commented on idvametrics/upload_metrics.py
> +    kwargs = {
The reason I went this route was because I was getting pylint errors due to having more than 7 arguments.

2022-05-19 21:03 UTC, dzaslavskiy commented on idvametrics/upload_metrics.py
> +    kwargs = {
maybe a config object or is a dictionary the pythonic way to do it?

2022-05-19 22:04 UTC, folksgl commented on idvametrics/upload_metrics.py
> +    kwargs = {
So any time you have more than about three arguments, you should probably ask yourself two questions:
  1: Is this function really doing **one** thing?
  2. Should this data be in its own object?

You may be able to encapsulate some of these fields in their own objects, but there doesn't seem to be an obvious large grouping here (to me at least). I still don't think kwargs should be used to hide the fact that a method has too many parameters though. There do seem to be come constants here that don't need to be arguments (I'm seeing document_keys, num_composite_buckets, index_pattern, event_message). 

The elasticsearch client probably should not be a parameter. As a general rule of thumb, any variable that's created and just sent to be part of an object, should probably be created by that object. So here I'd create an object to encapsulate the program args, and just let the CompositeAggregationQuery create the client internally.

2022-05-20 01:42 UTC, mikeisen1 commented on idvametrics/queries.py
> +connector_response_time = {
The query has been modified so it accurately pulls the data.

2022-05-20 01:46 UTC, mikeisen1 commented on .github/workflows/deploy-idvametrics.yaml
> +        run: cf push --vars-file vars.yaml
The only one that had been missing, FLOW_ID, has now been added.

2022-05-23 21:13 UTC, dzaslavskiy requested changes

2022-05-25 03:15 UTC, dzaslavskiy requested changes

2022-05-25 03:15 UTC, dzaslavskiy commented on idvametrics/analyticsconstants.py
> +FIVE_MINS = timedelta(minutes=5)
I know Garrett recommended this naming but i does not make sense to me here.

2022-05-25 03:15 UTC, dzaslavskiy commented on idvametrics/analytics_query.py
> +        return latest_timestamp
The returns seem to of differant types. Some commented code here.

2022-05-25 03:15 UTC, dzaslavskiy commented on idvametrics/analyticsutils.py
> +def convert_date_to_timestamp(
This is still a very confusing function. I think the conversion needs to be seperated from the timestamp source selection

2022-05-25 03:31 UTC, dzaslavskiy commented
The two queries implement different strategies for processing the data. ScanQuery retrieves all results first and then processes them. CompositeAgg query process the results as they are loaded. Could we simplify the code by moving CompositeAgg  to that pattern or is their an advantage to the way is it currently written?

2022-05-25 04:28 UTC, dzaslavskiy requested changes

2022-05-25 04:28 UTC, dzaslavskiy commented on idvametrics/analyticsconstants.py
> +SK_INDEX_PATTERN = "dev-skevents-*"
Two of these are index patterns and one is an index name or prefix. It seems as the code evolved some hardcoding of `-*` has crept in due to this difference.

2022-05-25 04:28 UTC, dzaslavskiy commented on idvametrics/analytics_query.py
> +        if not self.elasticsearch.indices.get_alias(f"{self.index_pattern}-*"):
Is self.index_pattern set to 'analytics' index? This would seem to be pointing at the wrong index

2022-05-25 04:28 UTC, dzaslavskiy commented on idvametrics/analytics_query.py
> +    def send_query_and_evaluate_results(self) -> None:
There are three steps here. query, build docs, upload. I think it would usefull to factor out the build into a function

2022-05-25 04:28 UTC, dzaslavskiy commented on idvametrics/analytics_query.py
> +    def __process_composite_aggregation_data(self, query_result: dict) -> str:
processing the docs and getting the after-key seem like seperate functions. It would be good to factor that out if that works.

2022-05-25 04:28 UTC, dzaslavskiy commented on idvametrics/analytics_query.py
> +    def __process_composite_aggregation_data(self, query_result: dict) -> str:
There are three two steps in here. Building the docs and sending requests to es. if those two are factored out and then called from `send_query_and_evaluate_results` that would help the two query types have more simliar structures

2022-05-25 04:33 UTC, dzaslavskiy commented on idvametrics/analytics_query.py
> +            get_recent_timestamp=self.__get_most_recent_timestamp,
you are passing in the function here which is certainly one way to do it. Is there some advantage vs passing in the result of the function?

2022-05-25 13:12 UTC, mikeisen1 commented on idvametrics/analytics_query.py
> +            get_recent_timestamp=self.__get_most_recent_timestamp,
If we pass in the function, we don't have to run the query unless the result is needed.

2022-05-25 13:13 UTC, mikeisen1 commented on idvametrics/analytics_query.py
> +        return latest_timestamp
the `parser.parse` and `datetime.now` functions both returns a value of type `datetime`.

2022-05-25 13:45 UTC, mikeisen1 commented on idvametrics/analyticsconstants.py
> +SK_INDEX_PATTERN = "dev-skevents-*"
The reason it has been that way is we only want the `dev-analytics` (and not `dev-analytics-*`) portion in `__process_composite_aggregation_data` where we upload the analytics document to the analytics index defined by a timestamp field.

2022-05-25 14:51 UTC, mikeisen1 commented on idvametrics/analytics_query.py
> +    def send_query_and_evaluate_results(self) -> None:
As per the Elasticsearch [docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-composite-aggregation.html#_size), we must split the retrieval into several requests as the number of composite buckets is unknown. We could increase the size of `DEFAULT_NUM_COMPOSITE_BUCKETS` and make it more likely all the results are retrieved at once, but there will still always be the issue of potentially having more than that number of buckets in the composite query result. I don't know of a python client helper function that allows us to write CompositeAggregationQuery similar to ScanQuery.

2022-05-25 16:43 UTC, mikeisen1 commented on idvametrics/analyticsconstants.py
> +FIVE_MINS = timedelta(minutes=5)
@dzaslavskiy and @folksgl, we could rename `FIVE_MINS` TO `ANALYTICS_TIME_OFFSET` and `ONE_DAY` to `INDEX_TIME_DIFFERENCE`. Thoughts?

2022-05-25 17:18 UTC, dzaslavskiy commented on idvametrics/analytics_query.py
> +            min_date = parser.parse(bucket["min"]["value_as_string"]).date()
I think the delete code should be factored out

2022-05-25 19:49 UTC, dzaslavskiy commented on idvametrics/analyticsconstants.py
> +FIVE_MINS = timedelta(minutes=5)
I think ANALYTICS_TIME_OFFSET is good. One day is used in delete action only right? I think that variable belongs in there.

2022-05-25 20:30 UTC, dzaslavskiy requested changes

2022-05-25 20:30 UTC, dzaslavskiy commented on idvametrics/analytics_query.py
> +    def __build_bulk_deletes_of_existing_documents(
return a list rather than append to list passed in

2022-05-25 20:30 UTC, dzaslavskiy commented on idvametrics/analytics_query.py
> +    def send_query_and_evaluate_results(self) -> None:
put the query code into a funtion that produces all the query results. __process_composite_aggregation_data is redeundant: the two calls in there can be pulled into the top level function. Also if you can come up with a more elegant name for this top level function that would be cool

2022-05-25 20:30 UTC, dzaslavskiy commented on idvametrics/analytics_query.py
> +        start_date = analyticsutils.get_datetime_from_str(
This date stuff is still doen't seem right. Lets discuss how we can make it better.

2022-05-25 20:30 UTC, dzaslavskiy commented on idvametrics/upload_metrics.py
> +"""
Some of the python files are snake case and some are lower case.

2022-05-26 16:55 UTC, folksgl commented on idvametrics/analyticsconstants.py
> +}
Unless these constants are used in multiple files, they should be kept as close to the code that uses them. I would move these back to the top of `uploadmetrics.py`.

2022-05-26 16:57 UTC, folksgl commented on idvametrics/uploadmetrics.py
> +from analyticsquery import CompositeAggregationQuery, ScanQuery
See my thoughts on this import style here: https://github.com/18F/identity-idva-gpo/pull/8#discussion_r882780747

2022-05-27 04:11 UTC, dzaslavskiy requested changes

2022-05-27 04:11 UTC, dzaslavskiy commented on idvametrics/analyticsquery.py
> +        while (
I think the condition can be
```
query_result := self.__query() and len(buckets := query_result["aggregations"]["composite_buckets"]["buckets"]) > 0  
```

2022-05-27 16:22 UTC, mikeisen1 commented on idvametrics/analyticsutils.py
> +    return int((parser.parse(date) - time_delta).timestamp())
It's a fun way to write that function but I don't think it's necessary.

2022-05-28 22:18 UTC, dzaslavskiy approved these changes

2022-05-31 18:46 UTC, merged