Support mfa in script
18F/identity-idva-monitoring pull request #205
Opened 2022-06-13 16:56 UTC by mikeisen1

Some environments in Ping require multi-factor authentication to login and obtain flow data. This PR adds support for MFA for the required environments while still allowing for simple login into environments that do not require MFA.

2022-06-13 21:47 UTC, dzaslavskiy commented on idvametrics/analyticsquery.py
> +        min_date: datetime.datetime = None,
why remove the type here?

2022-06-14 16:25 UTC, mikeisen1 commented on idvametrics/analyticsquery.py
> +        min_date: datetime.datetime = None,
Ah, that was mistakenly added.

2022-06-14 16:39 UTC, dzaslavskiy requested changes
To make it easier to keep track of the secrets in github, please prefix all the secrets used in idvametrics with METRICS_

2022-06-14 17:07 UTC, dzaslavskiy approved these changes

2022-06-14 17:07 UTC, merged