Feature/add drop off metric
18F/identity-idva-monitoring pull request #233
Opened 2022-07-21 19:22 UTC by mikeisen1

Add scripting to create a drop off metric for the dashboard.

2022-07-25 21:54 UTC, folksgl requested changes

2022-07-25 21:54 UTC, folksgl commented on idvametrics/analyticsquery.py
> +                ]
Is `e` short for something? `element` perhaps? Try to avoid one-letter variable names in all but the simplest for loops where `i` is a counter or similar situation.

2022-07-26 20:08 UTC, dzaslavskiy requested changes

2022-07-26 20:08 UTC, dzaslavskiy commented on idvametrics/README.md
> +### Nodes
Is title still used for identifying the node now that we are using description?

2022-07-26 20:08 UTC, dzaslavskiy commented on idvametrics/README.md
> +success or failure as defined above. The analytics connectors should not be used for
Analytics connectors may well be used for other purposes, Would that be an issue do to how they are processed?

2022-07-26 20:50 UTC, mikeisen1 commented on idvametrics/README.md
> +### Nodes
That is correct, and I can remove that from the README

2022-07-26 20:53 UTC, mikeisen1 commented on idvametrics/README.md
> +success or failure as defined above. The analytics connectors should not be used for
It shouldn't be as the elasticsearch queries should be written such that the query results and processing only takes in data from the nodes we want the data from.

2022-07-28 16:11 UTC, folksgl approved these changes
Should wait for @dzaslavskiy's ✅ as well

2022-08-02 15:55 UTC, dzaslavskiy approved these changes

2022-08-02 15:56 UTC, merged