add repo condition
18F/identity-idva-monitoring pull request #71
Opened 2021-11-05 22:08 UTC by folksgl

- Add repo owner condition
- Change reviewers to idva-partners

2021-11-08 06:08 UTC, dzaslavskiy requested changes

2021-11-08 06:08 UTC, dzaslavskiy commented on .github/workflows/update.yaml
> +      - name: Check Version of Alertmanager
wrong name

2021-11-09 17:13 UTC, dzaslavskiy commented on .cfignore
> +version_updater.sh
Does .cfignore in the root do anything? I was under the impression that it should be in the app directory?

2021-11-09 17:16 UTC, dzaslavskiy commented on version_updater.sh
> +#!/bin/bash
Perhaps a sub directory like https://github.com/18F/identity-idva-orchestration/tree/main/.cloud-gov

2021-11-09 17:17 UTC, dzaslavskiy submitted a review, later dismissed

2021-11-10 15:32 UTC, folksgl commented on version_updater.sh
> +#!/bin/bash
I decided against a sub-folder that would hide this script. The root directory of this repo is not being used to hold project or app code, so it really serves as good a place as any for this script. The only other place it _may_ go is in .github since it's being used by github actions to open a pr. But I don't particularly like the idea of stashing a script that's being used daily somewhere that people wouldn't think to look for it.

2021-11-10 15:36 UTC, dzaslavskiy approved these changes

2021-11-10 15:37 UTC, merged